using Random
using BenchmarkTools
using StaticArrays

include("Events3.jl")


# all possible states a person can be in
@enum Status susceptible infected recovered

# this is our agent type
mutable struct Person
    # state
    status :: Status
    # other agents this one can infect or be infected by
    contacts :: Vector{Person}
end

mutable struct World
	x :: Float64
end

# how we construct a person object
Person() = Person(susceptible, [])
Person(state) = Person(state, [])

mutable struct Simulation{ALT}
    # and this is our population of agents
    pop :: Vector{Person}
	alists :: ALT
end


@processes world::World begin
	@poisson(0.0001) ~
		true => @r(world)
	end

@processes person::Person world::World begin
    # recovery
    @poisson(1e-3)  ~
        person.status == infected           => 
            begin
                person.status = recovered
				@r(person)
				@r(person.contacts)
				@r(world)
				@kill(nothing)
	
            end

    # infection with rate proportional to prop. infected contacts
    @poisson(count(p -> p.status == infected, person.contacts)) ~
        # a person has to be susceptible in order to get infected
        person.status == susceptible        => 
            begin
                # status changes
                person.status = infected
                @r person person.contacts
            end

	@poisson(1e-2) ~
		person.status == infected =>
		begin
			person.status = recovered
			[person; person.contacts]
		end

	@poisson(1e-4) ~
		person.status == recovered		=>
			begin
				person.status = susceptible
				[person]
			end
	

	@poisson(1e-6) ~
		person.status == susceptible =>
			begin
				person.status = infected
				[person; person.contacts]
			end
	end

# this should be fine I think. The only situation where we need *global*
# information is for the global step function and possibly the type that
# holds all action lists, but those need only the list of types.
@model SIRM World Person


function setup_grid(constr, xs, ys)
	# construct the population (contactless for now)
	pop = [ constr(susceptible) for i in 1:xs*ys ]

	# make a matrix to simplify finding neighbours
	matrix = reshape(pop, ys, :)

	for x in 1:xs, y in 1:ys
		p = matrix[y, x]
		if x > 1
			push!(p.contacts, matrix[y, x-1])
		end
		if y > 1
			push!(p.contacts, matrix[y-1, x])
		end
		if x < xs
			push!(p.contacts, matrix[y, x+1])
		end
		if y < ys
			push!(p.contacts, matrix[y+1, x])
		end
	end

	pop
end

function spawn(sim)
    # spawn activates agents
    # this function was generated by the model declaration
    for person in sim.pop
		add_agent!(person, sim.alists[1], calc_rates(person))
    end

	w = World(0.0)
	add_agent!(w, sim.alists[2], PVT2(0.0001))
end

function create_sim(xs, ys)
    pop = setup_grid(Person, xs, ys)

    # create a simulation object with parameter values
	sim = Simulation(pop, (ActionList{Person, PVT1}(), ActionList{World, PVT2}()))
    
	sim.pop[1, 1].status = infected

	sim
end

function setup_sim(;xs, ys, seed, warmup=3000000)
	sim = create_sim(xs, ys)

	spawn(sim)

    # for reproducibility
    Random.seed!(seed)

	for i in 1:warmup
		step(sim)
	end

    sim
end


function run_sim(sim, n_steps)

	for i in 1:n_steps
		step(sim)
    end
end

function check_sum()
	# check correctness
	c = 0
	for i in 1:100
		sim = setup_sim(xs=100, ys=100, seed=i+42)
		run_sim(sim, 500000)
		c += count(p->p.status==recovered, sim.pop)
		print(".")
	end
	println; println(c/100)
end

function run_bench()
	i = 1
	for grid_size in [2, 4, 8, 16, 32, 64, 128, 256, 512]
		println("grid size: ", grid_size)
		@btime run_sim(sim, 500000) setup=(sim = setup_sim(xs=$grid_size, ys=$grid_size, seed=$i))
		i += 1
	end
end

#check_sum()
run_bench()


